### ISSUE TITLE
Plan for 0.2 FUCK TRUMP release

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#174]
Our next release is going to be pretty sweet - we have implemented a ton of new features, primarily improving the experience of a volunteer and massively streamlining the workflow for getting new images and officer identifications in our database. Here are some of the new features:

- [User accounts](https://github.com/lucyparsons/OpenOversight/pull/145)
- [File uploading directly in the application](https://github.com/lucyparsons/OpenOversight/pull/149)
- [Tagging directly in the application (bye bye janky google spreadsheet)](https://github.com/lucyparsons/OpenOversight/pull/169)
- [Leaderboard](https://github.com/lucyparsons/OpenOversight/pull/169)
- [User profiles](https://github.com/lucyparsons/OpenOversight/pull/169)
- [Moderation abilities for user tags and classifications by administrators](https://github.com/lucyparsons/OpenOversight/pull/169)

I think we should soon start testing on staging with what we have thus far. Good to have some lead time on this as there are a few new things on the devops side - S3, setting up the email - not big deals but certainly things to work into the deploy story. In addition, it would be really awesome if we could go live with the new release along with announcing "We have N new officer faces in our database", which I think is doable if we start adding tags in post merge of #169. Plus then we work out any kinks in the volunteer workflow. Here’s what I propose:

# Pre-release testing and data entry

  0.  Once PRs #168 and #169 get merged in, let’s deploy the develop branch to staging (involves a database migration)
1. Have myself and our LPL comrades that are interested make accounts on OO
2. We can submit all the good images from the Google drive and Github drive (which have been pre-sorted by volunteers in the Google spreadsheet) through the in-app upload form. If this is extremely onerous given the number of images, we can just add a smallish batch and we can redeploy after implementation of #150. 
3. We can get to tagging. Once tags exist, they will immediately appear in complainant search results (on staging).

As issues arise, we can fix them and write tests to guard against regressions. As users of the application realize other features would be useful (e.g. “hey it would be convenient if you could see the most recent 5 classifications on the app” or something) then we can implement the most pressing ones. In the meantime we can implement the smaller features (e.g. to throw a captcha up) and write unit tests to get coverage up as much as possible before we release 0.2 for realzies (edit: done in #179! if you want to write tests, I encourage functional tests of the volunteer workflow). 

# Release and deploy procedure

Then, to release 0.2.0 we will:

0. Backup the database
1.  If migrations are needed then we migrate
2. Deploy updated develop to staging
3. Do some manual testing again, if all looks good, tag and release
4. Destroy the prod db, copy over the staging db to prod to preserve all the images and tags we will have put in by then
5. Deploy to prod

# Remaining TODOs

- [x] Implement #150 (multiple file uploads)
- [x] Implement #148 (CAPTCHA and rate limiting)
- [x] If time permits, implement #90 and #26 (nice to have but not _super_ pressing, can push off to next release if necessary)
- [ ] Security audit (#79)
- [ ] Schedule backups (#118)

Comments/suggestions welcome!

**Comment by redshiftzero** [comment]
We can go ahead and deploy to staging w/o merge of #168

**Comment by freddymartinez9** [comment]
on it. I'll do the deploy to staging this morning.

**Comment by freddymartinez9** [comment]
Staging deployment failed. assigning to @redshiftzero for DB work.

**Comment by redshiftzero** [comment]
Thanks @freddymartinez9 - I think I know what the problem is, will dig around and fix. This is in my to do queue and will hopefully get to it today (but it might be tomorrow 😢 ).

**Comment by redshiftzero** [comment]
OK so I figure the migration got stuck on some of the old tables that were left in from when we populated the assignments and officers tables. These tables do not exist in the dev environment, and this `DOUBLE PRECISION` column in the error above is a data type from one of the columns in the old tables. I have removed these tables.

I also went ahead and cleaned out all the old tags and images - we'll need to reinsert them but this time through the app's image upload and interactive tagging tools. There aren't many so it shouldn't be hard (I am happy to do it). This will automatically do a few tasks like compute the hash of the image and add some image metadata columns. 

Documentation of what I did:

```
-- Delete all other tables, they're old
DROP TABLE base_assignments;
DROP TABLE base_roster;
DROP TABLE invisinst;

-- Remove old tags from faces (need to reinsert post-migration)
DELETE FROM faces;

-- Remove old images from faces
-- These need to get reuploaded to S3 using the image upload now in app
-- They are all in the root of our cpd_pictures github repo
DELETE FROM raw_images;
```

Give it a whirl again!

**Comment by redshiftzero** [comment]
Update: it worked and @freddymartinez9 was able to successfully deploy to staging. 🎉

**Comment by freddymartinez9** [comment]
Left to do:

0. update the `.env` to match new AWS and mail settings
1. Deploy updated develop to staging
2. Do some manual testing again, if all looks good, tag and release
3. Destroy the prod db, copy over the staging db to prod to preserve all the images and tags we will have put in by then
4. Deploy to prod with updated `.env`

This can be done in one sprint (assuming two week sprints if we really try hard)

**Comment by redshiftzero** [comment]
After resolution of #209, I can confirm that the entire volunteer tagging workflow is working great. Here are some screenshots because it's pretty exciting (to me at least...):

<img width="1179" alt="screen shot 2017-03-20 at 2 16 03 pm" src="https://cloud.githubusercontent.com/assets/7832803/24117515/88891434-0d78-11e7-97fc-14388b5f74a0.png">

<img width="1198" alt="screen shot 2017-03-20 at 2 17 56 pm" src="https://cloud.githubusercontent.com/assets/7832803/24117521/91263e1e-0d78-11e7-8c5d-51184d82e956.png">

Here's the data entry activities that need to get done:

- [ ] Upload all existing images and tag them - @redshiftzero in progress
- [ ] Upload all Flickr images from our social media surveillance - unassigned
- [ ] Upload all Twitter images from our social media surveillance - unassigned
- [ ] Upload all non-troll pictures from Google drive submission  - unassigned
- [ ] Sort and tag! - everyone

Also remember the app will tell you if you are submitting a duplicate image. We have a Google doc of initial officer identifications done for the Twitter and (most of) the submissions from activists so we should be working from this.

**Comment by redshiftzero** [comment]
Oh and one last note: if you're uploading images, remember _you must_ be logged in to OpenOversight (I still have the download link pointing to the Google form for users that are not logged in until I (or a contributor) puts a CAPTCHA on the submission route).

**Comment by redshiftzero** [comment]
Note I've uploaded everything from the `cpd_pictures` repository, except for the Twitter photos in `initial_scrape`

**Comment by redshiftzero** [comment]
We really have a LOT of stuff uploaded to S3 now, so we need to backup the S3 and postgres database ASAP. 

On my end for the release, going through the volunteer workflows today on staging has revealed a few small bugfixes I need to make (should be quick). Other than bugfixes, I'm going to implement #170 on the weekend and push the other items from the stretch goal to the next release (0.2.1). I might tweak a few design/UX things over the weekend but am not planning on any new features unless someone strongly objects and tells me some feature _needs_ to be implemented (tell me in the next few days please). We are now shooting for a launch on Wednesday next week. 

I want to assign the upload of the pre-sorted Twitter pictures to OpenOversight to someone and it's a bit of a rote task.

**Comment by redshiftzero** [comment]
OK everything that's getting done for 0.2 is done so I'm closing this. Note: tasks that didn't get done for 0.2:
- [ ] backups
- [ ] security audit
- [ ] upload of twitter images
- [ ] upload of google drive images

We will track these data entry / operations tasks in the [0.2 post release](https://github.com/lucyparsons/OpenOversight/projects/3) project.
